"""
Django settings for BKi project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
from django.conf import global_settings
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

IN_DEVELOPMENT = True
USE_LOCAL_DATABASE = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5e4duqk2)dkz_#+@1rwfp0*ujwi=-jp5nm5$gadi*26@vuiwgd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = IN_DEVELOPMENT
TEMPLATE_DEBUG = IN_DEVELOPMENT

ALLOWED_HOSTS = [] if IN_DEVELOPMENT else [] #FIXME: ALLOWED HOSTS - Fill with the right credentials

ADMINS = (('Daniel', 'email'), ) #FIXME: ADMINS - Fill with the right email


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'easy_thumbnails',
    'MainAPP',
    'Rebates',
    'Utilities',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'BKi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages', #TODO: Is the context processor of media required?
            ],
        },
    },
]

WSGI_APPLICATION = 'BKi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
} if USE_LOCAL_DATABASE else {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bki_rebates',
        'USER': 'django_bki',
        'PASSWORD': '%%*-285U|7Dz6eW',
        'HOST': 'localhost' #FIXME: Localhost?
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Media files (those which can be modified by the end-users)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR,  'media')

# Custom configuration for login and users
LOGIN_URL = '/login/'
AUTH_USER_MODEL = 'MainAPP.CustomUser'

AUTHENTICATION_BACKENDS = (
      'MainAPP.backends.CustomUserModelBackend',
  ) + global_settings.AUTHENTICATION_BACKENDS


# Django REST Framework configuration
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        'rest_framework.permissions.IsAdminUser',
    ]
}

# EASY_THUMBNAILS configuration
THUMBNAIL_DEBUG = IN_DEVELOPMENT

THUMBNAIL_ALIASES = {
    '': {
        '50x50': {'size': (50, 50), 'crop': True},
    },
}
